'use client'
import { RunnerGamePage } from 'Module'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function RunnerGame() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RunnerGamePage />
        </>
    )
}
